# Generated by Django 2.1 on 2018-08-08 00:20

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('strut', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='settings',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
    ]
